name: tests

on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-22.04
        strategy:
            fail-fast: true
            matrix:
              php: [7.3, 7.4, '8.0', 8.1, 8.2]
              laravel: [8, 9, 10]
              exclude:
                - php: 7.3
                  laravel: 9
                - php: 7.3
                  laravel: 10
                - php: 7.4
                  laravel: 9
                - php: 7.4
                  laravel: 10
                - php: '8.0'
                  laravel: 10
                - php: 8.2
                  laravel: 8

        name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
                  ini-values: error_reporting=E_ALL
                  tools: composer:v2
                  coverage: none

            - name: Setup problem matchers
              run: |
                  echo "::add-matcher::${{ runner.tool_cache }}/php.json"
                  echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"
            - name: Install dependencies
              run: |
                composer require "illuminate/support=^${{ matrix.laravel }}" --dev --no-update
                composer update --prefer-dist --no-interaction --no-progress
            - name: Execute tests
              run: vendor/bin/phpunit --verbose
